name: Main workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Build app
        run: ci/build-app.sh
      - name: Test app
        run: ci/unit-test-app.sh
      - name: Upload code artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
  Linting:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Run linting
        uses: super-linter/super-linter/slim@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
