name: Main workflow
on: push
env:
  docker_username: paul_mt
  docker_password: ${{ github.token }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Build app
        run: ci/build-app.sh
      - name: Test app
        run: ci/unit-test-app.sh
      - name: Upload code artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
  Linting:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Run linting
        uses: super-linter/super-linter/slim@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DISABLE_ERRORS: true
  Docker-image:
    runs-on: ubuntu-latest
    needs: Build
    permissions:
      packages: write
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Build docker image
        run: bash ci/build-docker.sh
      - name: Push docker image
        run: bash ci/push-docker.sh
