name: Main workflow
on: push
env:
  docker_username: paulmt
  docker_password: ${{ github.token }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Build app
        run: ci/build-app.sh
      - name: Test app
        run: ci/unit-test-app.sh
      - name: Upload code artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
  Linting:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Run linting
        uses: super-linter/super-linter/slim@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DISABLE_ERRORS: true
  Docker-image:
    runs-on: ubuntu-latest
    needs: Build
    permissions:
      packages: write
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: paulmt
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app
          push: true
          tags: ghcr.io/paulmt/micronaut-app:1.0-${{ github.sha }},ghcr.io/paulmt/micronaut-app:latest
  Component-test:
    runs-on: ubuntu-latest
    needs: Docker-image
    permissions:
      packages: read
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Execute component test
        run: bash ci/component-test.sh
  Performance-test:
    runs-on: ubuntu-latest
    needs: Docker-image
    permissions:
      packages: read
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Execute performance test
        run: bash ci/performance-test.sh
